### PR TITLE
[#5983] Fix bugs introduced in fbx export

### LINKED ISSUE #5983: Bug: FBX Exporting Error. After Commit number(5888).
For Testing Model.
[apples.zip](https://github.com/user-attachments/files/18582407/apples.zip)

That FBX model had been exported and reimported well.
but, after a commit below it is not.

Commits on Jan 14, 2025
[FBX] Allow export multi materials per node (https://github.com/assimp/assimp/pull/5888)

### PR DESCRIPTION
**Pull request by JulianKnodt**
There were some typos and incorrect offsets in a previous PR. This fixes part of it, correctly exporting the UV.

Closes #5983

### CODE REVIEW

File: code/AssetLib/FBX/FBXExporter.cpp [hunk 1]
```diff
@@ -1286,7 +1288,7 @@ void FBXExporter::WriteObjects () {
           indent = 3;
           FBX::Node::WritePropertyNode("Version", int32_t(101), outstream, binary, indent);
           FBX::Node::WritePropertyNode("Name", "", outstream, binary, indent);
-          FBX::Node::WritePropertyNode("MappingInformationType", "ByPolgonVertex", outstream, binary, indent);
+          FBX::Node::WritePropertyNode("MappingInformationType", "ByPolygonVertex", outstream, binary, indent);
```
Comment (JulianKnodt) [inline code/AssetLib/FBX/FBXExporter.cpp:1291]: 🫠

**Comment by JulianKnodt** [comment]
Are these changes cherry picked? I keep updating this PR but it goes out of date, so I'm a bit confused what's happening

**Comment by tellypresence** [comment]
Any news on this?

**Comment by JulianKnodt** [comment]
Are you asking reviewers or me? I'm still just waiting on review

**Review by kimkulling — APPROVED** [review]

**Comment by kimkulling** [comment]
Merged, thanks a lot for your contribution.
