### PR TITLE
Fix Stack-buffer-overflow READ in aiMaterial::AddBinaryProperty

### LINKED ISSUE #4447: Bug: Issue 45079 in oss-fuzz: assimp:assimp_fuzzer: Stack-buffer-overflow in aiMaterial::AddBinaryProperty
Status: New
Owner: ----
CC: kim.k...@[googlemail.com](http://googlemail.com/) 
Labels: Restrict-View-Commit ClusterFuzz Stability-Memory-AddressSanitizer Reproducible Engine-libfuzzer OS-Linux Security_Severity-Medium Proj-assimp Reported-2022-02-27
Type: Bug-Security

New issue 45079 by ClusterFuzz-External: assimp:assimp_fuzzer: Stack-buffer-overflow in aiMaterial::AddBinaryProperty
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=45079

Detailed Report: https://oss-fuzz.com/testcase?key=6520123362508800

Project: assimp
Fuzzing Engine: libFuzzer
Fuzz Target: assimp_fuzzer
Job Type: libfuzzer_asan_assimp
Platform Id: linux

Crash Type: Stack-buffer-overflow READ {*}
Crash Address: 0x7f3b8940bc54
Crash State:
  aiMaterial::AddBinaryProperty
  aiMaterial::AddProperty
  Assimp::MDLImporter::ParseSkinLump_3DGS_MDL7
  
Sanitizer: address (ASAN)

Recommended Security Severity: Medium

Crash Revision: https://oss-fuzz.com/revisions?job=libfuzzer_asan_assimp&revision=202202260608

Reproducer Testcase: https://oss-fuzz.com/download?testcase_id=6520123362508800

Issue filed automatically.

See https://google.github.io/oss-fuzz/advanced-topics/reproducing for instructions to reproduce this bug locally.
When you fix this bug, please
  * mention the fix revision(s).
  * state whether the bug was a short-lived regression or an old bug in any stable releases.
  * add any other useful information.
This information can help downstream consumers.

If you need to contact the OSS-Fuzz team with a question, concern, or any other feedback, please file an issue at https://github.com/google/oss-fuzz/issues. Comments on individual Monorail issues are not monitored.

This bug is subject to a 90 day disclosure deadline. If 90 days elapse
without an upstream patch, then the bug report will automatically
become visible to the public.

### PR DESCRIPTION
**Pull request by sashashura**
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=45079
Closes #4447 

The stack [buffer read overflow](https://github.com/assimp/assimp/blob/d9a8837a5b0e0d6b34b35a5bf1e1288ea23721aa/code/Material/MaterialSystem.cpp#L485) happens because the real `pInput` size is one byte less than `pSizeInBytes` in `aiMaterial::AddBinaryProperty`. The `pSizeInBytes` is [calculated](https://github.com/assimp/assimp/blob/d9a8837a5b0e0d6b34b35a5bf1e1288ea23721aa/code/Material/MaterialSystem.cpp#L528) as `static_cast<unsigned int>(pInput->length + 1 + 4)` which assumes that `pInput->length` doesn't include `\0` terminating character. This is in line with the [comment](https://github.com/assimp/assimp/blob/d9a8837a5b0e0d6b34b35a5bf1e1288ea23721aa/include/assimp/types.h#L393) in `aiString` for the member: `Binary length of the string excluding the terminal 0`. However in the case of `MDLImporter::ParseSkinLump_3DGS_MDL7` the aiString [is initialized as](https://github.com/assimp/assimp/blob/d9a8837a5b0e0d6b34b35a5bf1e1288ea23721aa/code/AssetLib/MDL/MDLMaterialLoader.cpp#L494-L499):
```cpp
        aiString szFile;
        const size_t iLen = strlen((const char *)szCurrent);
        size_t iLen2 = iLen + 1;
        iLen2 = iLen2 > MAXLEN ? MAXLEN : iLen2;
        memcpy(szFile.data, (const char *)szCurrent, iLen2);
        szFile.length = static_cast<ai_uint32>(iLen2);
```
When `iLen` is bigger or equal to `MAXLEN` the `szFile` length is set to `MAXLEN` and `data` contains non zero terminated characters. It is not entirely clear who breaks the contract, but I assume it is fair to expect aiString to have `\0` terminated data and fixed the implementation of `MDLImporter::ParseSkinLump_3DGS_MDL7`.

### CODE REVIEW

File: code/AssetLib/MDL/MDLMaterialLoader.cpp [hunk 1]
```diff
@@ -493,12 +493,12 @@ void MDLImporter::ParseSkinLump_3DGS_MDL7(
 
         aiString szFile;
         const size_t iLen = strlen((const char *)szCurrent);
-        size_t iLen2 = iLen + 1;
-        iLen2 = iLen2 > MAXLEN ? MAXLEN : iLen2;
+        size_t iLen2 = iLen > MAXLEN - 1 ? MAXLEN - 1: iLen;
```
Comment (turol) [inline code/AssetLib/MDL/MDLMaterialLoader.cpp:496]: You should add explicit parens here. I had to go look up C++ precedence rules to verify that this is correct. I think it is correct but people shouldn't have to do that.

**Review by kimkulling — APPROVED** [review]
Looks fine,

**Comment by kimkulling** [comment]
Merged, thanks a lot for your contribution.
