### PR TITLE
Fix warning abut inexistent warning

### LINKED ISSUE #6151: Warning C4619 (#pragma warning : there is no warning number 'number') with Visual Studio 2015 and newer
**Describe the technical debt**

In the following line the warning 4351 is diabled. However, this warning no longer exists in VS 2015 and newer

https://github.com/assimp/assimp/blob/536cd59807aa80515722ad176c9fb61b996e1355/include/assimp/defs.h#L177

same fore

https://github.com/assimp/assimp/blob/536cd59807aa80515722ad176c9fb61b996e1355/include/assimp/mesh.h#L55

**Better solution**

Only disable warning 4351 if MSVC is older than 2015

### PR DESCRIPTION
**Pull request by limdor**
These warnings are not existing before Visual Studio 2015

Fixes #6151

### CODE REVIEW

**Review by kimkulling — APPROVED** [review]
Looks fine.

File: code/AssetLib/Blender/BlenderIntermediate.h [hunk 1]
```diff
@@ -116,7 +116,7 @@ namespace Blender {
         mywrap arr;
     };
 
-#ifdef _MSC_VER
+#if _MSC_VER < 1500
```
Comment (TinyTinni) [inline code/AssetLib/Blender/BlenderIntermediate.h:119]: Why 1500 here and not 1900? Possible typo?

Comment (limdor) [reply code/AssetLib/Blender/BlenderIntermediate.h:119]: Correct, that is a typo. It should be 1900.

**Comment by limdor** [comment]
@kimkulling I had to push an update because there was an issue on the preprocessing macro that was missing the `defined(_MSC_VER)`. Can you retrigger the tests?
The problem is that if `_MSC_VER` is not defined, then the value when comparing is `0`. In places were the comparison is `_MSC_VER > x` it works even when it is not defined because it evaluates to false, but for cases where is `_MSC_VER < x` it is problematic because when `_MSC_VER ` is not defined it will evaluate to true.
